### ISSUE TITLE
Game SDK claims 'std' does not name a type (Godot 3.2.4 beta 4)

### ISSUE THREAD

**Issue by summertimejordi** [Drachenfrucht1/godotcord#20]
I'm experiencing errors when trying to compile Godot 3.2.4 with Godotcord on Ubuntu 20.10
![image](https://user-images.githubusercontent.com/12436824/103434969-27528e00-4bce-11eb-9501-755c041e50bc.png)
This is with a fresh clone of both Godot and Godotcord, after running setup.sh
I built with `scons -j6 platform=x11 target=release_debug use_lto=yes tools=yes`
Could this be an issue with Godotcord or with the Game SDK?

Does this compile on Linux for you @Drachenfrucht1?

Specs:
Godot 3.2.4 beta 4
Ubuntu 20.10

**Comment by summertimejordi** [comment]
After removing all parts of the GameSDK that use `std::` (for` example `std::int32_t` becomes `int32_t`) and adding `using namespace std;` to `types.h`, the engine compiles successfully. But when I try to run an empty scene in an empty project, I get the following error:
![image](https://user-images.githubusercontent.com/12436824/103435221-68986d00-4bd1-11eb-977e-58aacadcdb60.png)
Even though the file structure is correct:
![image](https://user-images.githubusercontent.com/12436824/103435227-78b04c80-4bd1-11eb-8345-6dd45125950e.png)

Any clue why this could be happening?

**Comment by summertimejordi** [comment]
> I'm experiencing errors when trying to compile Godot 3.2.4 with Godotcord on Ubuntu 20.10
> ![image](https://user-images.githubusercontent.com/12436824/103434969-27528e00-4bce-11eb-9501-755c041e50bc.png)
> This is with a fresh clone of both Godot and Godotcord, after running setup.sh
> I built with `scons -j6 platform=x11 target=release_debug use_lto=yes tools=yes`
> Could this be an issue with Godotcord or with the Game SDK?
> 
> Does this compile on Linux for you @Drachenfrucht1?
> 
> Specs:
> Godot 3.2.4 beta 4
> Ubuntu 20.10

Reproducible when compiling with 3.2.3 as well

**Comment by summertimejordi** [comment]
> After removing all parts of the GameSDK that use `std::` (for example `std::int32_t` becomes `int32_t`) and adding `using namespace std;` to `types.h`, the engine compiles successfully. But when I try to run an empty scene in an empty project, I get the following error:
> ![image](https://user-images.githubusercontent.com/12436824/103435221-68986d00-4bd1-11eb-977e-58aacadcdb60.png)
> Even though the file structure is correct:
> ![image](https://user-images.githubusercontent.com/12436824/103435227-78b04c80-4bd1-11eb-8345-6dd45125950e.png)
> 
> Any clue why this could be happening?

Also reproducible with 3.2.3

**Comment by summertimejordi** [comment]
> After removing all parts of the GameSDK that use `std::` (for example `std::int32_t` becomes `int32_t`) and adding `using namespace std;` to `types.h`, the engine compiles successfully. But when I try to run an empty scene in an empty project, I get the following error:
> ![image](https://user-images.githubusercontent.com/12436824/103435221-68986d00-4bd1-11eb-977e-58aacadcdb60.png)
> Even though the file structure is correct:
> ![image](https://user-images.githubusercontent.com/12436824/103435227-78b04c80-4bd1-11eb-8345-6dd45125950e.png)
> 
> Any clue why this could be happening?

Moving this to a separate issue

**Comment by Drachenfrucht1** [comment]
This is a problem with the header files provided by discord. The reason could be that only stdint.h is included. A quick google search said that only cstdint provides the fixed width integer types in the std namespace. 

An alternative to your fix is to include the cstdint header in the types.h file.
We could try to add a fix to the setup scripts as long as discord hasn't fixed this.

**Comment by summertimejordi** [comment]
> This is a problem with the header files provided by discord. The reason could be that only stdint.h is included. A quick google search said that only cstdint provides the fixed width integer types in the std namespace.
> 
> An alternative to your fix is to include the cstdint header in the types.h file.
> We could try to add a fix to the setup scripts as long as discord hasn't fixed this.

I'll try to add it to the setup scripts later today, I also confirmed the issue also happens on Windows, so I'll try to add it to the .bat file as well.

**Comment by summertimejordi** [comment]
@Drachenfrucht1 I fixed this issue in setup.sh (PR#24) but couldn't figure out how to do it in setup.bat since I'm not experienced with Batch files.
