### ISSUE TITLE
Error loading shared libraries on Linux

### ISSUE THREAD

**Issue by summertimejordi** [Drachenfrucht1/godotcord#22]
After removing all parts of the GameSDK that use `std::` (for example `std::int32_t` becomes `int32_t`) and adding `using namespace std;` to `types.h` (to fix #20), the engine compiles successfully. But when I try to run an empty scene in an empty project, I get the following error:
![image](https://user-images.githubusercontent.com/12436824/103435221-68986d00-4bd1-11eb-977e-58aacadcdb60.png)
Even though the file structure is correct:
![image](https://user-images.githubusercontent.com/12436824/103435227-78b04c80-4bd1-11eb-8345-6dd45125950e.png)

**Comment by Drachenfrucht1** [comment]
I think the error occurs because the godot instance that runs the scene isn't opened from the executable directory. An easy fix is to modify the rpath of the executable by running `patchelf --set-rpath '$ORIGIN' path/to/godot/executable` (similar to the last step for compilation on mac OS). I am currently trying to set the rpath correctly at compile time but nothing has worked so far.

**Comment by summertimejordi** [comment]
> I think the error occurs because the godot instance that runs the scene isn't opened from the executable directory. An easy fix is to modify the rpath of the executable by running `patchelf --set-rpath '$ORIGIN' path/to/godot/executable` (similar to the last step for compilation on mac OS). I am currently trying to set the rpath correctly at compile time but nothing has worked so far.

Does the rpath have to be absolute?

**Comment by Drachenfrucht1** [comment]
No, from my testing, a relative path in rpath is interpreted from the location the binary is executed. So if the rpath is set to `./` and I execute `bin/godot.x11.opt.tools.64`, only `./` would be searched for the shared binary but not `./lib`. $ORIGIN is replaced with the location of the binary not matter where I execute it. So when executing `bin/godot.x11.opt.tools.64`, `./bin` would be searched for the shared library

**Comment by summertimejordi** [comment]
Yeah I got it, Godot now successfully plays the scene without the error mentioned above, but I'm testing the Activity Manager and it's not working for me atm. Most likely not a problem related to this though so I'll see if I can get it sorted out.

**Comment by summertimejordi** [comment]
In the mean time can you look into merging #24 and #23
