### ISSUE TITLE
Add a way to get members who're in a lobby.

### ISSUE THREAD

**Issue by sairam4123** [Drachenfrucht1/godotcord#30]
Right now I'm trying to get the members in the lobby, but I can't find on how to do that, there's no documentation on how to do that or am I just being ignorant?

**Comment by Drachenfrucht1** [comment]
The only way to know who is in a lobby is to keep track of the members yourself (add when player joins, remove when player disconnects). There is, however, an internal array with all connected peers. I can add a method that returns the ids of the peers.

**Comment by sairam4123** [comment]
Cool. Thank you.

**Comment by sairam4123** [comment]
Can we talk in Discord?

**Comment by summertimejordi** [comment]
I think a discord group/server would be good for contributes and maintaining the repo easier

**Comment by sairam4123** [comment]
> The only way to know who is in a lobby is to keep track of the members yourself (add when player joins, remove when player disconnects). There is, however, an internal array with

Bit confused on how to do that. Any examples would be great.

I mean what signals are emitted when user joins and leaves.

**Comment by Drachenfrucht1** [comment]
`signal peer_connected(peer_id)` is emitted when someone joins.
`signal peer_disconnected(peer_id)` is emitted when someone disconnects.
I noticed they are not included in the documentation. I will add them later.

**Comment by sairam4123** [comment]
Oh thank you, it's too late for me right now, I'll check tomorrow.

**Comment by sairam4123** [comment]
Found you on discord. We'll continue the discussion there.
