### ISSUE TITLE
Implement User Manager, Overlays, Storage and Voice.

### ISSUE THREAD

**Issue by sairam4123** [Drachenfrucht1/godotcord#4]
Hello, I need to use this for production purposes, because I can't find any other discord game sdk wrapper, would you like to implement other stuffs as well?

Thank you very much for your help!

Stuff needs to be implemented in godotcord:
- [ ] Applications Manager #42 
- [x] Lobby Manager (WIP)
- [x] Storage Manager #44 
- [x] Voice Manager #54

**Comment by Drachenfrucht1** [comment]
My goal is to include every functionality of the Discord Game SDK. I'm currently implementing one manager after the other, as I have time. I can try to prioritize the ones you need.

**Comment by sairam4123** [comment]
Well, most of the things you did are enough for me, what I need right now is the Overlays and Users Manager. 

That's enough. 

And thank you for your reply.

**Comment by sairam4123** [comment]
Looks like you started working on UserManager thank you very much.

**Comment by sairam4123** [comment]
Glad you finished Users Manager.

**Comment by sairam4123** [comment]
Glad you finished Overlays Manager.

**Comment by sairam4123** [comment]
Hello, I recommend stop porting the managers and work on improving the current ones, I'm not even able to test them.

Only thing that works is, Activities.

Because of the lack of documentation, I spend 3hrs to create a multiplayer game, before realizing that a lot of features are missing. Like OpenNetwork and a lot more.

**Comment by sairam4123** [comment]
[DiscordMultiplayerGame.zip](https://github.com/Drachenfrucht1/godotcord/files/5745039/DiscordMultiplayerGame.zip)
Here's the project if you want.

**Comment by Drachenfrucht1** [comment]
Hi,
I downloaded your project and it runs fine on my maschine (Linux).
I have a simple app to test the functionality of all the managers that I will upload to github in the comming days.
This will hopefully help to understand how they can be included into your own project.

**Comment by sairam4123** [comment]
But it doesn't work on my machine, Windows 10 (1909)
I mean, it works, but when I try to press `join`, it doesn't join me.

**Comment by sairam4123** [comment]
#42 Applications manager

**Comment by sairam4123** [comment]
#44 Storage manager.

**Comment by Drachenfrucht1** [comment]
The Applications module is deprecated and will be removed from the Game SDK in the near future, so I will close this issue.

**Comment by sairam4123** [comment]
Actually all of the managers given here are deprecated, we must not support them in the Godot 4 rewrite of this project.
