### ISSUE TITLE
Use Signals instead of FuncRefs

### ISSUE THREAD

**Issue by sairam4123** [Drachenfrucht1/godotcord#55]
I feel like Signals has lots of advantages over function references.

Advantages:
1. Ability to use `yield` function.
2. Lot's of more advantages other than yield, I just forgot them, anyway.

Disadvantages:
1. Lots of signals in codes. It's taking one line to register a signal. (It's not really a disadvantage though 😛)

I don't feel any advantages and disadvantages though. Maybe we could discuss further on it. 

Thank you.

**Comment by Drachenfrucht1** [comment]
After reading the arguments presented on the discord server, I agree that signals are the more common concept in Godot at the moment. For version 4.0 there will be a new Object called `Callable` that will enable developers to pass functions as objects. I don't know how this will affect the use of signals. But I think that Godot 4.0 will nonetheless break this module, so we can decide this later for the 4.0 version of this module.
As for the Godot 3.0 version, we can change all FuncRefs to signals. 
For naming:
I would suggest either `FunctionName_callback` or `FunctionName_signal`.
