### ISSUE TITLE
Test Godotcord for Godot 3.3 release.

### ISSUE THREAD

**Issue by sairam4123** [Drachenfrucht1/godotcord#61]
As Godot is reaching 3.3, the current release 3.3rc9 went online 3 days ago, I'd recommend checking if Godotcord works with Godot version 3.3rc9 as well. 

Thank you.

**Comment by summertimejordi** [comment]
It works, I've been using it since 3.3 first started testing.

**Comment by summertimejordi** [comment]
None of Godotcord's features directly mix with existing features godot has, so we shouldn't need to worry about new godot versions messing with it unless they change something about how modules work.

**Comment by sairam4123** [comment]
Oh, that's great then!
Closing!
