### ISSUE TITLE
Use ReadTheDocs to host documentation.

### ISSUE THREAD

**Issue by sairam4123** [Drachenfrucht1/godotcord#71]
Hey, why not use ReadTheDocs, it's what Godot uses, and I'd recommend using it. Currently, I know you're using GitHub Pages, but it's better to use ReadTheDocs instead.

**Comment by sairam4123** [comment]
Well, we're currently writing docs seperately from XML docs right? We could just parse the XML Docs and post it on ReadTheDocs.

**Comment by Drachenfrucht1** [comment]
I agree with jordi. Using ReadTheDocs only adds unnecessary to this small scale project. 

I am also currently working on parsing the xml docs into markdown and updating the gh-pages branch automatically on the xml-docs branch. I just want to have a decent amount of the classes documented before merging.

**Comment by sairam4123** [comment]
Hmm, that's good indeed.
