### ISSUE TITLE
3.2.4?

### ISSUE THREAD

**Issue by huesonmcgee** [Drachenfrucht1/godotcord#8]
What's your expectation for this compiling successfully into Godot 3.2.4 once it comes out?  I can do it, just is there anything you foresee being a problem?

Thanks for this btw.  This is going to be a huge time savor for me and my team's project.

**Comment by Drachenfrucht1** [comment]
Glad you like the project!

I don't thank that Godot 3.2.4  will be a problem. Looking at the feature list, I can't see an item that could cause problems. 
I just compiled it with Godot 3.2.4 beta 2 and no errors or bugs occurred. However, if you encounter any bugs or errors, please report them here so I can fix them or open a pull request.

**Comment by huesonmcgee** [comment]
I'll run some tests with beta 2 at some point soon and post if I find anything.  We're waiting for it to come out of beta before switching over completely so if there's any issues I'd certainly post at that point.

**Comment by sairam4123** [comment]
I think beta 3 is out maybe test with it as well.

**Comment by sairam4123** [comment]
Tested with 3.2.4, everything working. @huesonmcgee So this issue can be closed.

**Comment by huesonmcgee** [comment]
Cool, done and done.
