### ISSUE TITLE
Code execution cannot proceed

### ISSUE THREAD

**Issue by huesonmcgee** [Drachenfrucht1/godotcord#9]
I'm thinking this is something wrong I did wrong but I figured I mention it here.  I've gotten everything working in a 3.2.1 build.  In the editor it works like a charm and is real easy to work with but once exported I haven't been able to get it past start up.  Godot tosses out a "This code execution cannot proceed because discord_game_sdk.dll was not found."  I've built export templates for it that have compiled fine and I've confirmed that the cpp and headers have made it in.  Am I missing something?

**Comment by Drachenfrucht1** [comment]
You need to copy the discord_game_sdk.dll into the folder with the game executable. When shipping your game to players, you also have to include the .dll file

**Comment by huesonmcgee** [comment]
Yep, that's it.  Don't mind me.
